WatchShop/WatchShop/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WatchShop.Models
{
    public class Brand
    {
        public int id { get; set; }
        [Required]
        [StringLength(255)]
        public string name { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}

WatchShop/WatchShop/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WatchShop.Models
{
    public class Item
    {
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        public long price { get; set; }
        public int brandId { get; set; }
        public virtual Brand Brand { get; set; }     
        [Required]
        public int categoryId { get; set; }
        public virtual Category Category { get; set; }
        public string image { get; set; }
    }
}

WatchShop/WatchShop/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WatchShop.Models;

namespace WatchShop.Controllers
{
    public class BrandController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: Brand
        public ActionResult Index()
        {
            List<Brand> listBrand = dbContext.Brands.ToList();//database
            return View(listBrand);
        }
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            dbContext.Brands.Add(brand);
            dbContext.SaveChanges();
            //luu vao database
            return RedirectToAction("Brands", "Admin");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = dbContext.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                dbContext.Entry(brand).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("Brands", "Admin");
            }
            return View(brand);
        }
        public ActionResult Delete(int id)
        {
            Brand exitstingBrand = dbContext.Brands.Where(temp => temp.id == id).FirstOrDefault();
            return View(exitstingBrand);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, Brand brand)
        {
            Brand exitstingBrand = dbContext.Brands.Where(temp => temp.id == id).FirstOrDefault();
            dbContext.Brands.Remove(exitstingBrand);
            dbContext.SaveChanges();
            return RedirectToAction("Brands", "Admin");
        }

        public ActionResult ListBrand()
        {
            var listBrand = from Brand in dbContext.Brands select Brand;
            return PartialView(listBrand);
        }

    }
}

WatchShop/WatchShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WatchShop.Models;

namespace WatchShop.Controllers
{
    public class CategoryController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: Category
        public ActionResult Index()
        {
            List<Category> listCategory = dbContext.Categories.ToList();//database
            return View(listCategory);
        }
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Category category)
        {
            dbContext.Categories.Add(category);
            dbContext.SaveChanges();
            //luu vao database
            return RedirectToAction("Categories", "Admin");
        }
        public ActionResult Delete(int id)
        {
            Category exitstingCategory = dbContext.Categories.Where(temp => temp.id == id).FirstOrDefault();
            return View(exitstingCategory);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, Category category)
        {
            Category exitstingCategory = dbContext.Categories.Where(temp => temp.id == id).FirstOrDefault();
            dbContext.Categories.Remove(exitstingCategory);
            dbContext.SaveChanges();
            return RedirectToAction("Categories", "Admin");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = dbContext.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,name")] Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Entry(category).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("Categories", "Admin");
            }
            return View(category);
        }
        public ActionResult ListCategory()
        {
            var listCategory = from Category in dbContext.Categories select Category;
            return PartialView(listCategory);
        }
        
    }
}

WatchShop/WatchShop/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WatchShop.Models;

namespace WatchShop.Controllers
{
    public class ItemController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: Item
        public ActionResult Index()
        {
            List<Item> listItem = dbContext.Items.ToList();//database
            return View(listItem);
        }

        public ActionResult Create()
        {
            var categories = dbContext.Categories.ToList();
            List<SelectListItem> categoryList = new List<SelectListItem>();
            foreach (Category item in categories)
            {
                categoryList.Add(new SelectListItem
                {
                    Text = item.name,
                    Value = item.id.ToString()
                });
            }
            ViewBag.Category = categoryList;

            var brands = dbContext.Brands.ToList();
            List<SelectListItem> brandList = new List<SelectListItem>();
            foreach (Brand item in brands)
            {
                brandList.Add(new SelectListItem
                {
                    Text = item.name,
                    Value = item.id.ToString()
                });
            }
            ViewBag.Brand = brandList;
            return View();

        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Item item)
        {
            dbContext.Items.Add(item);
            dbContext.SaveChanges();
            //luu vao database
            return RedirectToAction("Items", "Admin");
        }

        public ActionResult Detail(int id)
        {
            Item item = dbContext.Items.Find(id);//database
            return View("Detail", item);
        }
        public ActionResult Delete(int id)
        {
            Item exitstingItem = dbContext.Items.Where(temp => temp.id == id).FirstOrDefault();
            return View(exitstingItem);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, Item item)
        {
            Item exitstingItem = dbContext.Items.Where(temp => temp.id == id).FirstOrDefault();
            dbContext.Items.Remove(exitstingItem);
            dbContext.SaveChanges();
            return RedirectToAction("Items", "Admin");
        }

        public ActionResult Edit(int? id)
        {
            var categories = dbContext.Categories.ToList();
            List<SelectListItem> categoryList = new List<SelectListItem>();
            foreach (Category c in categories)
            {
                categoryList.Add(new SelectListItem
                {
                    Text = c.name,
                    Value = c.id.ToString()
                });
            }
            ViewBag.Category = categoryList;

            var brands = dbContext.Brands.ToList();
            List<SelectListItem> brandList = new List<SelectListItem>();
            foreach (Brand b in brands)
            {
                brandList.Add(new SelectListItem
                {
                    Text = b.name,
                    Value = b.id.ToString()
                });
            }
            ViewBag.Brand = brandList;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = dbContext.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);

        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,name,price,brandId,categoryId,image")] Item item)
        {
            if (ModelState.IsValid)
            {
                dbContext.Entry(item).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("Items", "Admin");
            }
            return View(item);
        }
        public ActionResult ItemByCategory(int id)
        {
            var item = from i in dbContext.Items where i.categoryId == id select i;
            return View(item);
        }
        public ActionResult ItemByBrand(int id)
        {
            var item = from i in dbContext.Items where i.brandId == id select i;
            return View(item);
        }
    }
}

WatchShop/WatchShop/Views/Admin/Brands.cshtml
@model IEnumerable<WatchShop.Models.Brand>

@{
    ViewBag.Title = "Brands";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Brands</h2>

<p>
    @Html.ActionLink("Create Brand", "Create","Brand")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.ActionLink("Edit","Edit","Brand", new { id = item.id }, new { @class = ""}) |
            @Html.ActionLink("Delete", "Delete","Brand", new { id=item.id }, new { @class = "" })
        </td>
    </tr>
}

</table>

WatchShop/WatchShop/Views/Admin/Categories.cshtml
@model IEnumerable<WatchShop.Models.Category>
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Categories</h2>
<p>
    @Html.ActionLink("Create Category", "Create","Category")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit","Category", new { id = item.id }, new { @class = "" }) |
                @Html.ActionLink("Delete", "Delete", "Category", new { id = item.id }, new { @class = "" })
            </td>
        </tr>
    }

</table>

WatchShop/WatchShop/Views/Admin/DeleteBrand.cshtml
@model WatchShop.Models.Brand

@{
    ViewBag.Title = "DeleteBrand";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>DeleteBrand</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Brands")
        </div>
    }
</div>

WatchShop/WatchShop/Views/Admin/DeleteCategory.cshtml
@model WatchShop.Models.Category

@{
    ViewBag.Title = "DeleteCategory";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>DeleteCategory</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WatchShop/WatchShop/Views/Admin/DeleteItem.cshtml
@model WatchShop.Models.Item

@{
    ViewBag.Title = "DeleteItem";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>DeleteItem</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <p><strong>Brand: </strong>@Html.DisplayFor(model => model.Brand.name)</p>

        <p><strong>Category: </strong>@Html.DisplayFor(model => model.Category.name)</p>

        <p><strong>Watch Name: </strong>@Html.DisplayFor(model => model.name)</p>

        <p><strong>Price: </strong>@Html.DisplayFor(model => model.price)</p>

        <p><strong>Image: </strong><img src="@Html.DisplayFor(model => model.image)" /></p>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Items")
        </div>
    }
</div>

WatchShop/WatchShop/Views/Admin/EditBrand.cshtml
@model WatchShop.Models.Brand

@{
    ViewBag.Title = "EditBrand";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>EditBrand</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Brands")
</div>

WatchShop/WatchShop/Views/Admin/EditCategory.cshtml
@model WatchShop.Models.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>EditCategory</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Categories")
</div>

WatchShop/WatchShop/Views/Admin/EditItem.cshtml
@model WatchShop.Models.Item

@{
    ViewBag.Title = "EditItem";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>EditItem</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brandId, "brandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.brandId, (IEnumerable<SelectListItem>)ViewBag.Brand, new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.brandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryId, (IEnumerable<SelectListItem>)ViewBag.Category, new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Items")
</div>

WatchShop/WatchShop/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Đây là trang chủ Admin</h1>
<h1>Tới trang người dùng: @Html.ActionLink("Go", "Index", "Home") </h1>

WatchShop/WatchShop/Views/Admin/Items.cshtml
@model IEnumerable<WatchShop.Models.Item>

@{
    ViewBag.Title = "Items";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<button type="button" class="btn btn-primary mt-1">@Html.ActionLink("Create Item", "Create", "Item")</button>

<div class="row mt-4">
    <div class="col-lg-12">
        <div class="table-responsive table--no-card m-b-30">
            <table class="table table-borderless table-striped table-earning">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.name)</td>
                            <td><img src="@Html.DisplayFor(modelItem => item.image)" style="width:50px;height:auto;"></td>
                            <td>@Html.DisplayFor(modelItem => item.price)</td>
                            <td>
                                <pre style="font-size: 16px; font-family: Poppins, sans-serif; color: #808080;">@Html.ActionLink("Edit", "Edit", "Item", new { id = item.id },new { id = "cc", Style = "color: #808080"})  | @Html.ActionLink("Delete", "Delete","Item",new { id = item.id },new {id = "cc", Style = "color: #808080"})</pre>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>